#!/bin/sh

EDirUser=$HOME/.enlightenment
[ -d $EDirUser ] || exit 1
EDirRoot=/usr/share/enlightenment


[ "$LANG" != "$(cat $EDirUser/menus/lang)" ] && \
	$EDirRoot/scripts/e_gen_menu && exit


MD5=$(find /usr/share/applications/ -name "*.desktop" \
        -exec cat "{}" ";" | md5sum)

[ "$MD5" != "$(cat $EDirUser/menus/md5)" ] && \
	$EDirRoot/scripts/e_gen_menu
	
